---
ops: [train, evaluate]
model: {
    path: ./src/selene/selene_models.py,
        class: ReverseComplementDeepSEA,
    
    class_args: {
        sequence_length: 1000,
        channel_size_factor: 160,
        n_targets: 919,
        reverse_complement_prop: [
            [0.0, 0.0, 1.0],
            [0.0, 0.0, 0.0],
            [0.0, 0.0, 0.0],
            [0.0, 0.0, 0.0],
            [0.0, 0.0, 0.0],
        ],
    },
    # non_strand_specific: mean
}
sampler: !obj:selene_sdk.samplers.MultiFileSampler {
    train_sampler: !obj:selene_sdk.samplers.file_samplers.MatFileSampler {
        filepath: data/deepsea/train.mat,
        sequence_key: trainxdata,
        targets_key: traindata,
        sequence_batch_axis: 2,
        sequence_alphabet_axis: 1,
        targets_batch_axis: 1,
        shuffle: True,
        random_seed: 12
    },
    validate_sampler: !obj:selene_sdk.samplers.file_samplers.MatFileSampler {
        filepath: data/deepsea/valid.mat,
        sequence_key: validxdata,
        targets_key: validdata,
        sequence_batch_axis: 0,
        sequence_alphabet_axis: 1,
        targets_batch_axis: 0,
        shuffle: False
    },
    test_sampler: !obj:selene_sdk.samplers.file_samplers.MatFileSampler {
        filepath: data/deepsea/test.mat,
        sequence_key: testxdata,
        targets_key: testdata,
        sequence_batch_axis: 0,
        sequence_alphabet_axis: 1,
        targets_batch_axis: 0,
        shuffle: False
    },
    features: !obj:selene_sdk.utils.load_features_list {
        input_path: data/deepsea/deepsea_predictor_names.txt
    }
}
train_model: !obj:selene_sdk.TrainModel {
    batch_size: 20,
    max_steps: 20000, 
    report_stats_every_n_steps: 1000,
    n_validation_samples: 8000,  # matches the number of samples in `valid.mat`
    n_test_samples: 455024,  # matches the number of samples in `test.mat`
    use_cuda: True,
    data_parallel: True,
    report_gt_feature_n_positives: 50,
    logging_verbosity: 2
}
random_seed: 1447
output_dir: ./outputs/src/selene/training_outputs
create_subdirectory: False
load_test_set: False
...
