---
ops: [train, evaluate]
model: {
    path: ./src/selene/selene_models.py,
        class: CopyKernelDeepSEA,
    
    class_args: {
        sequence_length: 1000,
        n_targets: 1,
        encode_model_config: {
            'model': 'Multilayer',
            'kernel_len': 9,
            'latent_len': 200,
            'seq_len': 64,
            'seq_per_batch': 200,
            'input_dropout_freq': 0.0,
            'latent_noise_std': 0.0,
            'neighbour_loss_prop': 0.0,
            'load_prev_model_state': 'outputs/src/ae/experiment/aemdchr22Multilayer9x200d0.03n0.2l0.0_30001at1.0_0-30000.pth',
            'hidden_len': 24,
            'pool_size': 4,
            'n_conv_and_pool': 1,
            'n_conv_before_pool': 2,
            'n_linear': 2,
            'use_cuda_if_available': True,
            'hidden_dropout_freq': 0.05,
        },
        encode_n_layers: 7,
        deepsea_n_layers: 1,
        channel_size_factor: 10,
    },
    non_strand_specific: mean
}
sampler: !obj:selene_sdk.samplers.IntervalsSampler {
    reference_sequence: !obj:selene_sdk.sequences.Genome {
                        input_path: ./data/selene/male.hg19.fasta
    },
    features: !obj:selene_sdk.utils.load_features_list {
        input_path: ./data/selene/distinct_features.txt
    },
    target_path: ./data/selene/sorted_GM12878_CTCF.bed.gz,
    intervals_path: ./data/selene/deepsea_TF_intervals.txt,
    seed: 127,
            sample_negative: True,
        sequence_length: 1000,
    center_bin_to_predict: 200,
    test_holdout: [chr8, chr9],
    validation_holdout: [chr6, chr7],
            feature_thresholds: 0.5,
    mode: train,
    save_datasets: [validate, test]
}
train_model: !obj:selene_sdk.TrainModel {
    batch_size: 48,
    max_steps: 100,      report_stats_every_n_steps: 10,
    n_validation_samples: 1280,
    n_test_samples: 4096,
    cpu_n_threads: 8,
    use_cuda: False,
    data_parallel: False
}
random_seed: 1447
output_dir: ./outputs/src/selene/training_outputs
create_subdirectory: False
load_test_set: False
...
