---
ops: [evaluate]
model: {
    path: models/deepsea_arch.py,
    class: DeepSEA,
    class_args: {
        weights_filename: models/deepsea_predict.pth,
        save_update_to_file: models/deepsea_predict_updated_weights.pth,
    },
    non_strand_specific: mean
}
sampler: !obj:selene_sdk.samplers.IntervalsSampler {
    reference_sequence: !obj:selene_sdk.sequences.Genome {
        input_path: online_data/male.hg19.fa,
        blacklist_regions: hg19
    },
    features: !obj:selene_sdk.utils.load_features_list {
        input_path: online_data/distinct_features.txt
    },
    target_path: online_data/sorted_deepsea_data.bed.gz, 
    intervals_path: online_data/TF_intervals.txt,
    test_holdout: [chr8, chr9],
    validation_holdout: [chr6, chr7],
    seed: 127,
    sequence_length: 1000,
    center_bin_to_predict: 200,
    feature_thresholds: 0.5,
    mode: train,
    save_datasets: [train, test, validate]
}
evaluate_model: !obj:selene_sdk.EvaluateModel {
    batch_size: 64,
    features:  !obj:selene_sdk.utils.load_features_list {
        input_path: online_data/distinct_features.txt
    },
    use_cuda: True, 
    report_gt_feature_n_positives: 50,
    trained_model_path: models/deepsea_predict_updated_weights.pth,
    output_dir: evaluation_outputs
}
output_dir: online_sampler_outputs
random_seed: 1447
create_subdirectory: False
...
