---
ops: [train, evaluate]
model: {
    path: ./src/selene/selene_models.py,
        class: ReverseComplementDeepSEA,
    
    class_args: {
        sequence_length: 1000,
        channel_size_factor: 4,
        n_targets: 1,
        reverse_complement_prop: [
            [0.0, 0.0, 0.5],
            [0.0, 0.5, 0.0],
            [0.0, 0.5, 0.0],
            [0.0, 0.0, 0.0],
            [0.0, 0.0, 0.0],
        ],
        max_pool: False,
    },
    non_strand_specific: mean
}
sampler: !obj:selene_sdk.samplers.IntervalsSampler {
    reference_sequence: !obj:selene_sdk.sequences.Genome {
                        input_path: ./data/selene/male.hg19.fasta
    },
    features: !obj:selene_sdk.utils.load_features_list {
        input_path: ./data/selene/distinct_features.txt
    },
    target_path: ./data/selene/sorted_GM12878_CTCF.bed.gz,
    intervals_path: ./data/selene/deepsea_TF_intervals.txt,
    seed: 127,
            sample_negative: True,
    sequence_length: 1000,
        center_bin_to_predict: 200,
    test_holdout: [chr8, chr9],
    validation_holdout: [chr6, chr7],
            feature_thresholds: 0.5,
    mode: train,
    save_datasets: [validate, test]
}
train_model: !obj:selene_sdk.TrainModel {
    batch_size: 40,
    max_steps: 20000,
    report_stats_every_n_steps: 1000,
    n_validation_samples: 12000,
    n_test_samples: 480000,
    cpu_n_threads: 16,
    use_cuda: False,
    data_parallel: False
}
random_seed: 1447
output_dir: ./outputs/src/selene/training_outputs
create_subdirectory: False
load_test_set: False
...
